import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import { Movies } from '../components/Movies/Movies';
import styles from '../styles/Home.module.css';

const Main = styled.main`
    height: calc(100% - 4rem);
    background-color: ${({ theme }) => theme.bg.body};
    color: ${({ theme }) => theme.text.primary};
`;

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
                <link rel='preconnect' href='https://fonts.gstatic.com' />
                <link
                    href='https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap'
                    rel='stylesheet'
                />
                <link
                    href='https://fonts.googleapis.com/icon?family=Material+Icons'
                    rel='stylesheet'
                />
            </Head>

            <Main>
                <Movies />
            </Main>
        </div>
    );
};

export default Home;
